backend:
  name: github
  repo: wupangyen/pang-blog-minimal-mistakes-theme-githubpages
  branch: main
  base_url: https://pang-blog-minimal-mistakes-theme.onrender.com
  auth_endpoint: /auth
  token_endpoint: /auth/token
  app_id: Ov23liQqy3xfIgwcvHhQ

media_folder: "images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "single" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "single" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Audio", name: "audio", widget: "file", required: false,media_folder: "/images", public_folder: "/images"}
      - { label: "Body", name: "body", widget: "markdown" }